'use client'

function Badge({ value }) {
  if (!value) return null
  const lower = value.toLowerCase()
  const cls = lower === 'high' ? 'badge-high' : lower === 'medium' ? 'badge-medium' : lower === 'low' ? 'badge-low' : ''
  return <span className={`badge ${cls}`}>{value}</span>
}

function SubList({ items }) {
  if (!items?.length) return null
  return (
    <ul style={{ listStyle: 'none', paddingLeft: 20, margin: '4px 0 0' }}>
      {items.map((item, i) => <li key={i}>– {item}</li>)}
    </ul>
  )
}

const li = { marginBottom: 8, listStyle: 'none' }
const ul = { listStyle: 'none', padding: 0, margin: 0 }
const sub = { listStyle: 'none', paddingLeft: 20, margin: '4px 0 0' }

export default function Report({ session, onStartOver }) {
  const {
    validatedProblemStatement, rootCauseAnalysis, researchDecision,
    researchSynthesis, strategicAnalysis, recommendation,
  } = session

  const hasResearch = researchDecision?.researchRequired !== false && researchSynthesis

  async function handleDownloadPDF() {
    const html2pdf = (await import('html2pdf.js')).default
    const element = document.getElementById('report-content')
    html2pdf().set({
      margin: 12,
      filename: 'gatekeeper-report.pdf',
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
    }).from(element).toPdf().get('pdf').then((pdf) => {
      const total = pdf.internal.getNumberOfPages()
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      pdf.setFontSize(8)
      pdf.setTextColor(156, 163, 175)
      for (let i = 1; i <= total; i++) {
        pdf.setPage(i)
        pdf.text(
          'Generated by AI Gatekeeper · Built by Sarah Douglas · github.com/VictoriusSecret · linkedin.com/in/sarahbdouglas/',
          pageW / 2,
          pageH - 8,
          { align: 'center' }
        )
      }
    }).save()
  }

  return (
    <div className="container-wide" style={{ paddingTop: 40 }}>
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 32 }}>
        <h1>Gatekeeper Report</h1>
        <div style={{ display: 'flex', gap: 12 }}>
          <button className="btn-primary" onClick={handleDownloadPDF}>Download PDF</button>
          <button className="btn-secondary" onClick={onStartOver}>Start over</button>
        </div>
      </div>

      <div id="report-content">

        {/* 1. Executive Summary */}
        <div className="report-section">
          <h2>1. Executive Summary</h2>
          {recommendation && (
            <ul style={ul}>
              <li style={li}>• <strong>Recommended Path:</strong> {recommendation.recommendedPath?.primaryApproach}
                {recommendation.recommendedPath?.supportingApproaches?.length > 0 && (
                  <ul style={sub}>
                    {recommendation.recommendedPath.supportingApproaches.map((a, i) => (
                      <li key={i}>– Supporting: {a}</li>
                    ))}
                  </ul>
                )}
              </li>
              <li style={li}>• <strong>Rationale:</strong> {recommendation.rationale}</li>
              <li style={li}>• Confidence: <Badge value={recommendation.confidence?.rating} />{recommendation.confidence?.rationale ? ` — ${recommendation.confidence.rationale}` : ''}</li>
              <li style={li}>• <strong>Next Step:</strong> {recommendation.nextStep}</li>
            </ul>
          )}
        </div>

        <hr className="section-divider" />

        {/* 2. Problem Definition */}
        <div className="report-section">
          <h2>2. Problem Definition</h2>
          <ul style={ul}>
            <li style={li}>• <strong>Validated Problem Statement:</strong> {validatedProblemStatement}</li>
            {strategicAnalysis?.problemSignificance && (
              <li style={li}>• Problem Significance: <Badge value={strategicAnalysis.problemSignificance.rating} />{strategicAnalysis.problemSignificance.rationale ? ` — ${strategicAnalysis.problemSignificance.rationale}` : ''}</li>
            )}
          </ul>
        </div>

        <hr className="section-divider" />

        {/* 3. Root Cause Analysis */}
        <div className="report-section">
          <h2>3. Root Cause Analysis</h2>
          {rootCauseAnalysis && (
            <ul style={ul}>
              <li style={li}>• <strong>Primary Root Cause:</strong> {rootCauseAnalysis.primaryRootCause?.category}
                {rootCauseAnalysis.primaryRootCause?.rationale && (
                  <ul style={sub}><li>– {rootCauseAnalysis.primaryRootCause.rationale}</li></ul>
                )}
              </li>
              {rootCauseAnalysis.contributingFactors?.length > 0 && (
                <li style={li}>• <strong>Contributing Factors:</strong>
                  <ul style={sub}>
                    {rootCauseAnalysis.contributingFactors.map((f, i) => (
                      <li key={i} style={{ marginBottom: 4 }}>– <strong>{f.category}:</strong> {f.rationale}</li>
                    ))}
                  </ul>
                </li>
              )}
              <li style={li}>• Confidence: <Badge value={rootCauseAnalysis.confidence} /></li>
              {rootCauseAnalysis.evidence?.length > 0 && (
                <li style={li}>• <strong>Evidence:</strong>
                  <SubList items={rootCauseAnalysis.evidence} />
                </li>
              )}
              {rootCauseAnalysis.assumptions?.length > 0 && (
                <li style={li}>• <strong>Assumptions:</strong>
                  <SubList items={rootCauseAnalysis.assumptions} />
                </li>
              )}
            </ul>
          )}
        </div>

        <hr className="section-divider" />

        {/* 4. Research Findings — hidden if no research */}
        {hasResearch && (
          <>
            <div className="report-section">
              <h2>4. Research Findings</h2>
              <ul style={ul}>
                <li style={li}>• Market Maturity: <Badge value={researchSynthesis.marketMaturity?.rating} />{researchSynthesis.marketMaturity?.rationale ? ` — ${researchSynthesis.marketMaturity.rationale}` : ''}</li>
                <li style={li}>• Vendor Landscape: <Badge value={researchSynthesis.vendorLandscape?.rating} />{researchSynthesis.vendorLandscape?.rationale ? ` — ${researchSynthesis.vendorLandscape.rationale}` : ''}</li>
                <li style={li}>• AI Market Signals: <Badge value={researchSynthesis.aiMarketSignals?.rating} />{researchSynthesis.aiMarketSignals?.rationale ? ` — ${researchSynthesis.aiMarketSignals.rationale}` : ''}</li>
                {researchSynthesis.keyResearchFindings?.length > 0 && (
                  <li style={li}>• <strong>Key Research Findings:</strong>
                    <SubList items={researchSynthesis.keyResearchFindings} />
                  </li>
                )}
                {researchSynthesis.failurePatternSummary?.length > 0 && (
                  <li style={li}>• <strong>Common Failure Patterns:</strong>
                    <SubList items={researchSynthesis.failurePatternSummary} />
                  </li>
                )}
              </ul>
            </div>
            <hr className="section-divider" />
          </>
        )}

        {/* 5. Strategic Analysis */}
        <div className="report-section">
          <h2>{hasResearch ? '5' : '4'}. Strategic Analysis</h2>
          {strategicAnalysis && (
            <ul style={ul}>
              {strategicAnalysis.solutionLandscape?.alternativesEvaluated?.length > 0 && (
                <li style={li}>• <strong>Alternatives Evaluated:</strong>
                  <ul style={sub}>
                    {strategicAnalysis.solutionLandscape.alternativesEvaluated.map((alt, i) => (
                      <li key={i} style={{ marginBottom: 6 }}>
                        – <strong>{alt.approach}</strong> <Badge value={alt.fit} />
                        {(alt.rationale || alt.keyTradeoffs?.length > 0) && (
                          <ul style={{ listStyle: 'none', paddingLeft: 16, margin: '2px 0 0' }}>
                            {alt.rationale && <li>{alt.rationale}</li>}
                            {alt.keyTradeoffs?.length > 0 && <li>Tradeoffs: {alt.keyTradeoffs.join(' · ')}</li>}
                          </ul>
                        )}
                      </li>
                    ))}
                  </ul>
                </li>
              )}
              {strategicAnalysis.solutionLandscape?.alternativesNotEvaluated?.length > 0 && (
                <li style={li}>• <strong>Alternatives Not Evaluated:</strong>
                  <ul style={sub}>
                    {strategicAnalysis.solutionLandscape.alternativesNotEvaluated.map((alt, i) => (
                      <li key={i}>– <strong>{alt.approach}:</strong> {alt.reason}</li>
                    ))}
                  </ul>
                </li>
              )}
              <li style={li}>• Build vs Buy: <Badge value={strategicAnalysis.buildVsBuy?.recommendedApproach} />{strategicAnalysis.buildVsBuy?.rationale ? ` — ${strategicAnalysis.buildVsBuy.rationale}` : ''}</li>
              {strategicAnalysis.economicConsiderations && (
                <li style={li}>• <strong>Economic Considerations:</strong>
                  <ul style={sub}>
                    <li>– Implementation Cost: <Badge value={strategicAnalysis.economicConsiderations.implementationCost} /></li>
                    <li>– Operational Cost: <Badge value={strategicAnalysis.economicConsiderations.operationalCost} /></li>
                    <li>– Time to Value: <Badge value={strategicAnalysis.economicConsiderations.timeToValue} /></li>
                    <li>– Opportunity Cost: <Badge value={strategicAnalysis.economicConsiderations.opportunityCost} /></li>
                    {strategicAnalysis.economicConsiderations.rationale && (
                      <li>{strategicAnalysis.economicConsiderations.rationale}</li>
                    )}
                  </ul>
                </li>
              )}
              {strategicAnalysis.humanImpact && (
                <li style={li}>• <strong>Human Impact:</strong>
                  <ul style={sub}>
                    {strategicAnalysis.humanImpact.capabilityEnhancement && <li>– Capability enhancement: {strategicAnalysis.humanImpact.capabilityEnhancement}</li>}
                    {strategicAnalysis.humanImpact.capabilityRisk && <li>– Capability risk: {strategicAnalysis.humanImpact.capabilityRisk}</li>}
                    {strategicAnalysis.humanImpact.humanJudgmentRequirements && <li>– Judgment requirements: {strategicAnalysis.humanImpact.humanJudgmentRequirements}</li>}
                    {strategicAnalysis.humanImpact.knowledgeRetentionConsiderations && <li>– Knowledge retention: {strategicAnalysis.humanImpact.knowledgeRetentionConsiderations}</li>}
                  </ul>
                </li>
              )}
              <li style={li}>• AI Assessment: <Badge value={strategicAnalysis.aiAssessment?.rating} />{strategicAnalysis.aiAssessment?.rationale ? ` — ${strategicAnalysis.aiAssessment.rationale}` : ''}</li>
              {strategicAnalysis.strategicInsights?.length > 0 && (
                <li style={li}>• <strong>Strategic Insights:</strong>
                  <SubList items={strategicAnalysis.strategicInsights} />
                </li>
              )}
            </ul>
          )}
        </div>

        <hr className="section-divider" />

        {/* 6. Recommendation */}
        <div className="report-section">
          <h2>{hasResearch ? '6' : '5'}. Recommendation</h2>
          {recommendation && (
            <ul style={ul}>
              <li style={li}>• <strong>Recommended Path:</strong> {recommendation.recommendedPath?.primaryApproach}
                {recommendation.recommendedPath?.supportingApproaches?.length > 0 && (
                  <ul style={sub}>
                    {recommendation.recommendedPath.supportingApproaches.map((a, i) => (
                      <li key={i}>– Supporting: {a}</li>
                    ))}
                  </ul>
                )}
              </li>
              <li style={li}>• <strong>Root Cause Alignment:</strong> {recommendation.rootCauseAlignment}</li>
              {recommendation.alternativesNotSelected?.length > 0 && (
                <li style={li}>• <strong>Alternatives Not Selected:</strong>
                  <ul style={sub}>
                    {recommendation.alternativesNotSelected.map((alt, i) => (
                      <li key={i}>– <strong>{alt.approach}:</strong> {alt.reasonNotSelected}</li>
                    ))}
                  </ul>
                </li>
              )}
              {recommendation.risks?.length > 0 && (
                <li style={li}>• <strong>Risks:</strong>
                  <SubList items={recommendation.risks} />
                </li>
              )}
              <li style={li}>• Confidence: <Badge value={recommendation.confidence?.rating} />{recommendation.confidence?.rationale ? ` — ${recommendation.confidence.rationale}` : ''}</li>
              <li style={li}>• <strong>Next Step:</strong> {recommendation.nextStep}</li>
            </ul>
          )}
        </div>

      </div>
    </div>
  )
}
